server:
  port: 8091
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: manger
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aale?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    cache: true
    charset: utf-8
    content-type: text/html;charset=UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    allow-session-override: true
    suffix: .html
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      default_encoding: UTF-8
      number_format: 0.##########
      auto_import: common/common.ftl as common
      template_exception_handler: ignore
      template_update_delay: 0

  druid:
    max-active: 30
    min-idle: 5
    maxWait: 10000
    validationQuery: SELECT 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    #spring 默认jackson返回时区与当前相差8个小时
    time-zone: GMT+8




